# Generated by Django 5.2.8 on 2025-12-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity_int', models.IntegerField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hours_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lot',
                'managed': False,
            },
        ),
    ]
